#!/bin/sh

fake() {
  echo 'Starting auto-runner...'
  echo 'Considering /Users/josh/deleteme/clojure-koans/src/koans/01_equalities.clj...'
  echo 'Considering /Users/josh/deleteme/clojure-koans/src/koans/02_strings.clj...'
  echo 'Considering /Users/josh/deleteme/clojure-koans/src/koans/03_lists.clj...'
  echo 'Considering /Users/josh/deleteme/clojure-koans/src/koans/04_vectors.clj...'
  # sleep 0.5
  echo 'Considering /Users/josh/deleteme/clojure-koans/src/koans/05_sets.clj...'
  echo 'Considering /Users/josh/deleteme/clojure-koans/src/koans/06_maps.clj...'
  # sleep 0.5
  echo 'Considering /Users/josh/deleteme/clojure-koans/src/koans/07_functions.clj...'
  echo 'Considering /Users/josh/deleteme/clojure-koans/src/koans/08_conditionals.clj...'
  echo 'Considering /Users/josh/deleteme/clojure-koans/src/koans/09_higher_order_functions.clj...'
  echo 'Considering /Users/josh/deleteme/clojure-koans/src/koans/10_runtime_polymorphism.clj...'
  echo 'Considering /Users/josh/deleteme/clojure-koans/src/koans/11_lazy_sequences.clj...'
  echo 'Considering /Users/josh/deleteme/clojure-koans/src/koans/12_sequence_comprehensions.clj...'
  echo 'Considering /Users/josh/deleteme/clojure-koans/src/koans/13_creating_functions.clj...'
  echo 'Considering /Users/josh/deleteme/clojure-koans/src/koans/14_recursion.clj...'
  # sleep 1
  echo ''
  echo 'Now meditate upon /Users/josh/deleteme/clojure-koans/src/koans/14_recursion.clj'
  echo '---------------------'
  echo 'Assertion failed!'
  echo 'clojure.lang.ExceptionInfo: Recursion ends with a base case'
  echo '(= true (is-even? 0)) {:line 25}, compiling:(/Users/josh/deleteme/clojure-koans/src/koans/14_recursion.clj:23:1)'
}


fake | "$(dirname $0)/hilite"

